sudo: false
language: python
os: linux
install:
- &upgrade_python_toolset pip install --upgrade pip setuptools wheel
- &install_test_deps pip install --upgrade pytest pytest-sugar
- &install_deps pip install -r CI_REQUIREMENTS.txt
- pip install --upgrade pytest-cov coveralls

_python:
- &python34
  name: "Python 3.4"
  python: "3.4"
- &python35
  name: "Python 3.5"
  python: "3.5"
- &python36
  name: "Python 3.6"
  python: "3.6"
- &python37
  name: "Python 3.7"
  python: "3.7"
  dist: xenial
  sudo: true
- &pypy3
  name: "PyPy3"
  python: "pypy3.5"

_helpers:
- &install_cython pip install --upgrade Cython
- &build_package python setup.py bdist_wheel
- &install_built pip install threaded --no-index -f dist
- &test_no_cov  py.test -vv test
- &test_cythonized
  stage: Test cythonized
  install:
  - *upgrade_python_toolset
  - *install_test_deps
  - *install_deps
  - *install_cython
  script:
  - *build_package
  - *install_built
  - *test_no_cov
  after_success: skip

- &static_analysis
  stage: Static analysis
  <<: *python37
  after_success: skip

- &code_style_check
  stage: Code style check
  <<: *python37
  after_success: skip

script:
- pip install -e .
- py.test -vv --cov-config .coveragerc --cov-report= --cov=threaded test
- coverage report -m --fail-under 87
after_success:
- coveralls

jobs:
  include:
  - <<: *static_analysis
    name: "PyLint"
    install:
    - *upgrade_python_toolset
    - *install_deps
    - pip install --upgrade "pylint >= 2.2"
    script:
    - pylint threaded
  - <<: *static_analysis
    name: "Bandit"
    install:
    - *upgrade_python_toolset
    - pip install --upgrade bandit
    script:
    - bandit -r threaded
  - <<: *static_analysis
    name: "MyPy"
    install:
    - *upgrade_python_toolset
    - *install_deps
    - pip install --upgrade "mypy >= 0.660"
    script:
    - mypy --strict threaded
  - <<: *static_analysis
    name: "PEP8"
    install:
    - *upgrade_python_toolset
    - pip install --upgrade flake8
    script:
    - flake8

  - <<: *code_style_check
    name: "PEP257"
    install:
    - *upgrade_python_toolset
    - pip install --upgrade pydocstyle
    script:
    - pydocstyle threaded
  - <<: *code_style_check
    name: "Black formatting"
    install:
    - *upgrade_python_toolset
    - pip install --upgrade black
    script:
    - black --check threaded

  - stage: test
    <<: *python34
  - stage: test
    <<: *python35
  - stage: test
    <<: *python36
  - stage: test
    <<: *python37
  - stage: test
    <<: *pypy3

  - <<: *test_cythonized
    <<: *python34
  - <<: *test_cythonized
    <<: *python35
  - <<: *test_cythonized
    <<: *python36
  - <<: *test_cythonized
    <<: *python37

  - stage: deploy
    # This prevents job from appearing in test plan unless commit is tagged:
    if: tag IS present
    # Run on pypy to build not cythonized wheel
    <<: *pypy3
    name: Build universal and cythonized bdist_wheel. Deploy bdist and sdist.
    services:
    - docker
    install:
    - *upgrade_python_toolset
    script:
    - ./tools/run_docker.sh "threaded"
    before_deploy:
    - pip install -r build_requirements.txt
    - *build_package
    deploy:
    - provider: pypi
      # `skip_cleanup: true` is required to preserve binary wheels, built
      # inside of manylinux1 docker container during `script` step above.
      skip_cleanup: true
      user: penguinolog
      password:
        secure: "h1gXulNJxdjdUtPXDwUf/2MltjjiTy/cSsv+67Bxr9PAXSo9s0ynnhijKavE0QlKPr0NDJcEcl79dEN3gx1rkbAFZ+YRJfx0KHy26ImNAIx+npOFjGko87KhMNkrE3QBn9carWNnjYA4rCuUqbv/Znk9xixleE/sHJbKnkkTrerSI2jkznMa6h0FNVCEPzFesHmll7rBy4CjFkRcWNX8nfKNIV9rHFI7mXm8+jzl0msOnkEcKRqAk+MUwVjcD9XtpF42uA0nQTtqjWFdwSUxxBJKMyrkkI0o8Uk06EewkgJGwjGpvn+EUm1hBpjGrXUQQJyr20SZdC0CqaqXD/axISAtQPzP5I4Ey3VkLDV4mZuQjeNlbRbTH0Q7af+CpnOpFtYobIs1/HjB5wztazegT8uk4ZU/GheYqknXmtg9Ga8NV47sIpLC/hTLXWP+O/k0JKRYP9CgjTml2nLykNjZy4KRnlCUerYH8d4bNz687ElXU2bLtlBxyigUc9oo31DvNG+vB2axOp8wGiRTEpfBVPEF6EYUj+qSbX4ep4o/mWp+ax5YlLVYVoXkXpNecIggICAChIkqEl9MtGzTu31s3sBKpk9WuqoyHG80TDo2Tet6zWYx3itUx9M0SLkrML9Hs5WKsXDZE6jZrVHtx8lWuuZZl5JQkXYtd358lwJmEBM="
      on:
        tags: true
        distributions: sdist
      skip_upload_docs: true
      skip_existing: true

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
