sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install tox-travis
  - pip install coveralls
script: tox
after_success:
  - coveralls
before_deploy:
  - pip install -r requirements.txt
