sudo: false
language: python
os: linux
install:
- &upgrade_python_toolset pip install --upgrade pip setuptools wheel
- pip install --upgrade pytest pytest-sugar
- &install_deps pip install -r CI_REQUIREMENTS.txt
- pip install --upgrade pytest-cov coveralls

_python:
- &python27
  name: "Python 2.7"
  python: "2.7"
- &pypy
  name: "PyPy"
  python: "pypy"
- &python37
  name: "Python 3.7"
  python: "3.7"
  dist: xenial
  sudo: true

_helpers:
- &build_package python setup.py bdist_wheel

- &static_analysis
  stage: Static analysis
  <<: *python27
  after_success: skip

- &code_style_check
  stage: Code style check
  <<: *python27
  after_success: skip

script:
- pip install -e .
- py.test -vv --cov-config .coveragerc --cov-report= --cov=threaded test
- coverage report -m --fail-under 87
after_success:
- coveralls

jobs:
  include:
  - <<: *static_analysis
    name: "PyLint"
    install:
    - *upgrade_python_toolset
    - *install_deps
    - pip install --upgrade "pylint < 2.0"
    script:
    - pylint threaded
  - <<: *static_analysis
    name: "Bandit"
    install:
    - *upgrade_python_toolset
    - pip install --upgrade bandit
    script:
    - bandit -r threaded
  - <<: *static_analysis
    <<: *python37
    name: "MyPy"
    install:
    - *upgrade_python_toolset
    - *install_deps
    - pip install --upgrade "mypy >= 0.660"
    script:
    - mypy --strict threaded
  - <<: *static_analysis
    name: "PEP8"
    install:
    - *upgrade_python_toolset
    - pip install --upgrade flake8
    script:
    - flake8

#  - <<: *code_style_check
#    name: "PEP257"
#    install:
#    - *upgrade_python_toolset
#    - pip install --upgrade pydocstyle
#    script:
#    - pydocstyle threaded

  - stage: test
    <<: *python27
  - stage: test
    <<: *pypy
    allow_failure: true

  - stage: deploy
    # This prevents job from appearing in test plan unless commit is tagged:
    if: tag IS present
    <<: *pypy
    name: Build universal bdist_wheel. Deploy bdist and sdist.
    services: []
    install:
    - *upgrade_python_toolset
    - pip install -r build_requirements.txt
    script:
    - *build_package
    before_deploy: []
    deploy:
    - provider: pypi
      # `skip_cleanup: true` is required to preserve binary wheels, built
      # inside of manylinux1 docker container during `script` step above.
      skip_cleanup: true
      user: penguinolog
      password:
        secure: "h1gXulNJxdjdUtPXDwUf/2MltjjiTy/cSsv+67Bxr9PAXSo9s0ynnhijKavE0QlKPr0NDJcEcl79dEN3gx1rkbAFZ+YRJfx0KHy26ImNAIx+npOFjGko87KhMNkrE3QBn9carWNnjYA4rCuUqbv/Znk9xixleE/sHJbKnkkTrerSI2jkznMa6h0FNVCEPzFesHmll7rBy4CjFkRcWNX8nfKNIV9rHFI7mXm8+jzl0msOnkEcKRqAk+MUwVjcD9XtpF42uA0nQTtqjWFdwSUxxBJKMyrkkI0o8Uk06EewkgJGwjGpvn+EUm1hBpjGrXUQQJyr20SZdC0CqaqXD/axISAtQPzP5I4Ey3VkLDV4mZuQjeNlbRbTH0Q7af+CpnOpFtYobIs1/HjB5wztazegT8uk4ZU/GheYqknXmtg9Ga8NV47sIpLC/hTLXWP+O/k0JKRYP9CgjTml2nLykNjZy4KRnlCUerYH8d4bNz687ElXU2bLtlBxyigUc9oo31DvNG+vB2axOp8wGiRTEpfBVPEF6EYUj+qSbX4ep4o/mWp+ax5YlLVYVoXkXpNecIggICAChIkqEl9MtGzTu31s3sBKpk9WuqoyHG80TDo2Tet6zWYx3itUx9M0SLkrML9Hs5WKsXDZE6jZrVHtx8lWuuZZl5JQkXYtd358lwJmEBM="
      on:
        tags: true
        distributions: sdist
      skip_upload_docs: true
      skip_existing: true

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
