sudo: false
language: python
os: linux
install:
- &upgrade_python_toolset pip install --upgrade pip setuptools wheel
- &install_test_deps pip install --upgrade pytest pytest-sugar
- &install_deps pip install -r CI_REQUIREMENTS.txt
- pip install --upgrade pytest-cov coveralls

_helpers:
- &install_cython pip install --upgrade Cython
- &build_package python setup.py bdist_wheel
- &install_built pip install threaded --no-index -f dist
- &test_no_cov  py.test -vv test
- &test_cythonized
  install:
  - *upgrade_python_toolset
  - *install_test_deps
  - *install_deps
  - *install_cython
  script:
  - *build_package
  - *install_built
  - *test_no_cov
  after_success: skip

script:
- pip install -e .
- py.test -vv --cov-config .coveragerc --cov-report= --cov=threaded test
- coverage report -m --fail-under 90
after_success:
- coveralls

jobs:
  fast_finish: true
  include:
  - stage: test
    name: "Python 3.4"
    python: 3.4
  - stage: test
    name: "Python 3.5"
    python: 3.5
  - stage: test
    name: "Python 3.6"
    python: 3.6
  - stage: test
    name: "Python 3.7"
    python: 3.7
    dist: xenial
    sudo: true
  - stage: test
    name: "PyPy3"
    python: pypy3.5

  - stage: Static analisys
    name: "PyLint"
    python: 3.6
    services: []
    install:
    - *upgrade_python_toolset
    - *install_deps
    - pip install --upgrade "pylint >= 2.0"
    script:
    - pylint threaded
    after_success: skip
  - stage: Static analisys
    name: "Bandit"
    python: 3.6
    services: []
    install:
    - *upgrade_python_toolset
    - pip install --upgrade bandit
    script:
    - bandit -r threaded
    after_success: skip
  - stage: Static analisys
    name: "MyPy"
    python: 3.7
    dist: xenial
    sudo: true
    services: []
    install:
    - *upgrade_python_toolset
    - *install_deps
    - pip install --upgrade "mypy >= 0.620"
    script:
    - mypy --strict threaded
    after_success: skip

  - stage: Test cythonized
    name: "Python 3.4"
    python: 3.4
    <<: *test_cythonized
  - stage: Test cythonized
    name: "Python 3.5"
    python: 3.5
    <<: *test_cythonized
  - stage: Test cythonized
    name: "Python 3.6"
    python: 3.6
    <<: *test_cythonized
  - stage: Test cythonized
    name: "Python 3.7"
    python: 3.7
    dist: xenial
    sudo: true
    <<: *test_cythonized

  - stage: Code style check
    name: "PEP8"
    python: 3.6
    install:
    - *upgrade_python_toolset
    - pip install --upgrade flake8
    script:
    - flake8
    after_success: skip
  - stage: Code style check
    name: "PEP257"
    python: 3.6
    install:
    - *upgrade_python_toolset
    - pip install --upgrade pydocstyle
    script:
    - pydocstyle threaded
    after_success: skip

  - stage: deploy
    # This prevents job from appearing in test plan unless commit is tagged:
    if: tag IS present
    # Run on pypy to build not cythonized wheel
    python: pypy3.5
    services:
    - docker
    install:
    - *upgrade_python_toolset
    script:
    - ./tools/run_docker.sh "threaded"
    before_deploy:
    - pip install -r build_requirements.txt
    - *build_package
    deploy:
    - provider: pypi
      # `skip_cleanup: true` is required to preserve binary wheels, built
      # inside of manylinux1 docker container during `script` step above.
      skip_cleanup: true
      user: penguinolog
      password:
        secure: "h1gXulNJxdjdUtPXDwUf/2MltjjiTy/cSsv+67Bxr9PAXSo9s0ynnhijKavE0QlKPr0NDJcEcl79dEN3gx1rkbAFZ+YRJfx0KHy26ImNAIx+npOFjGko87KhMNkrE3QBn9carWNnjYA4rCuUqbv/Znk9xixleE/sHJbKnkkTrerSI2jkznMa6h0FNVCEPzFesHmll7rBy4CjFkRcWNX8nfKNIV9rHFI7mXm8+jzl0msOnkEcKRqAk+MUwVjcD9XtpF42uA0nQTtqjWFdwSUxxBJKMyrkkI0o8Uk06EewkgJGwjGpvn+EUm1hBpjGrXUQQJyr20SZdC0CqaqXD/axISAtQPzP5I4Ey3VkLDV4mZuQjeNlbRbTH0Q7af+CpnOpFtYobIs1/HjB5wztazegT8uk4ZU/GheYqknXmtg9Ga8NV47sIpLC/hTLXWP+O/k0JKRYP9CgjTml2nLykNjZy4KRnlCUerYH8d4bNz687ElXU2bLtlBxyigUc9oo31DvNG+vB2axOp8wGiRTEpfBVPEF6EYUj+qSbX4ep4o/mWp+ax5YlLVYVoXkXpNecIggICAChIkqEl9MtGzTu31s3sBKpk9WuqoyHG80TDo2Tet6zWYx3itUx9M0SLkrML9Hs5WKsXDZE6jZrVHtx8lWuuZZl5JQkXYtd358lwJmEBM="
      on:
        tags: true
        distributions: sdist
      skip_upload_docs: true

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
